{
 "title": "Revenue dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Wins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dsp_wins_total", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "dsp_budget", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Clicks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dsp_clicks_total", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "BidValue/PotentialRevenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "dsp_bid_ratio", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Conversions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "dsp_conversions_total", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Errors(validation + timeouts)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": " sum by (dsp) (dsp_losses_total{reason=~\"timeout|response_error\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}