{
 "title": "Revenue dashboard (ext)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Revenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dsp_revenue", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "BidValue/PotentialRevenue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "dsp_bid_ratio", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dsp_budget", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "dsp_response_time", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Wins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "dsp_wins_total", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Losses(nobid)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "dsp_losses_total{reason=\"nobid\"}",
     "legendFormat": "{{dsp}}"
    }
   ]
  },
  {
   "title": "Clicks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "dsp_clicks_total", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Losses(response_error)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "dsp_losses_total{reason=\"response_error\"}",
     "legendFormat": "{{dsp}}"
    }
   ]
  },
  {
   "title": "Conversions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "dsp_conversions_total", "legendFormat": "{{dsp}}" }
   ]
  },
  {
   "title": "Losses(forbidden)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "dsp_losses_total{reason=\"forbidden\"}",
     "legendFormat": "{{dsp}}"
    }
   ]
  },
  {
   "title": "Losses(timeout)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "dsp_losses_total{reason=\"nobid\"}",
     "legendFormat": "{{dsp}}"
    }
   ]
  }
 ]
}