HTTP_CODE_DSP_RESPONSE_TIMEOUT = 408
HTTP_CODE_DSP_RESPONSE_UNKNOWN_ERROR = 477

LOSS_REASON_BID_RESPONSE_ERROR = 'response_error'
LOSS_REASON_BID_RESPONSE_TIMEOUT_ERROR = 'timeout'
LOSS_REASON_SMALL_BID = 'small_bid'
LOSS_REASON_NO_BID = 'nobid'
LOSS_REASON_FORBIDDEN = 'forbidden'

